// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using kıvıl.Context;

#nullable disable

namespace kıvıl.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240529214606_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("kıvıl.Entities.Hasta", b =>
                {
                    b.Property<int>("HastaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HastaId"));

                    b.Property<bool>("AileGecmisi")
                        .HasColumnType("bit");

                    b.Property<bool>("AlkolKullanımı")
                        .HasColumnType("bit");

                    b.Property<string>("Cinsiyet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EgzersizYapıyorMu")
                        .HasColumnType("bit");

                    b.Property<string>("Isim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("KalpKriziRiski")
                        .HasColumnType("bit");

                    b.Property<bool>("SigaraKullanımı")
                        .HasColumnType("bit");

                    b.Property<string>("Soyisim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Yas")
                        .HasColumnType("int");

                    b.HasKey("HastaId");

                    b.ToTable("Hastalar");
                });

            modelBuilder.Entity("kıvıl.Entities.Test", b =>
                {
                    b.Property<int>("TestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TestId"));

                    b.Property<int>("HastaId")
                        .HasColumnType("int");

                    b.Property<int>("KanBasıcı")
                        .HasColumnType("int");

                    b.Property<int>("KanSekeri")
                        .HasColumnType("int");

                    b.Property<int>("Kolestrol")
                        .HasColumnType("int");

                    b.HasKey("TestId");

                    b.HasIndex("HastaId")
                        .IsUnique();

                    b.ToTable("Testler");
                });

            modelBuilder.Entity("kıvıl.Entities.Test", b =>
                {
                    b.HasOne("kıvıl.Entities.Hasta", "Hasta")
                        .WithOne("Test")
                        .HasForeignKey("kıvıl.Entities.Test", "HastaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hasta");
                });

            modelBuilder.Entity("kıvıl.Entities.Hasta", b =>
                {
                    b.Navigation("Test")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
